- name: Create Config File
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item}}"
    url: http://172.31.7.194:8080
    user: admin
    password: "{{jenkins_passsword}}"
    loop:
      - frontend
      - catalogue
      - user
      - cart
      - shipping
      - payment
      - dispatch